name: Release

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release Binary and Docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Fix git permissions
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}